### ISSUE TITLE
branch 관리 포인트 잡기

### ISSUE THREAD

**Issue by parkyounghwan** [Nexters/AZ-Server#6]
- [x] master / develop / deploy / ... 의 branch 별 용도 협의.
- [x] branch 별로 pull request 후, merge 시 commiter 수 만큼 확인 받는 방식 논의.

*참고
[Git에 대해 알아보자 5. GitHub 추가 기능들](https://cupjoo.tistory.com/11)

**Comment by parkyounghwan** [comment]
'master' 로 default 브랜치 변경

**Comment by chlalstjd430** [comment]
저희 브랜치 전략이 [git-flow](https://woowabros.github.io/experience/2017/10/30/baemin-mobile-git-branch-strategy.html) 아니었나용?

**Comment by parkyounghwan** [comment]
아 나는 깃 플로우가 어떤 흐름 말하는 건줄 알았어 ㅋㅋ 방법론이 있군 확인요 정리하고 클로즈 할게요~

**Comment by chlalstjd430** [comment]
넵~!

**Comment by KimHunJin** [comment]
브랜치 전략은 나중에 변경해도 충분히 가능해서 첨부터 너무 복잡하게 생각하지 않아도 됩니다 :)

**Comment by parkyounghwan** [comment]
네 스승님!

2020년 7월 17일 (금) 오전 11:13, Kim HunJin (Mos) <notifications@github.com>님이 작성:

**Comment by KimHunJin** [comment]
왜 다 스승이래!! 으ㅏㅏㅏㅏㄱ

**Comment by parkyounghwan** [comment]
처음에는 master와 develop 브랜치가 존재합니다. 물론 develop 브랜치는 master에서부터 시작된 브랜치입니다. develop 브랜치에서는 상시로 버그를 수정한 커밋들이 추가됩니다. 새로운 기능 추가 작업이 있는 경우 develop 브랜치에서 feature 브랜치를 생성합니다. feature 브랜치는 언제나 develop 브랜치에서부터 시작하게 됩니다. 기능 추가 작업이 완료되었다면 feature 브랜치는 develop 브랜치로 merge 됩니다. develop에 이번 버전에 포함되는 모든 기능이 merge 되었다면 QA를 하기 위해 develop 브랜치에서부터 release 브랜치를 생성합니다. QA를 진행하면서 발생한 버그들은 release 브랜치에 수정됩니다. QA를 무사히 통과했다면 release 브랜치를 master와 develop 브랜치로 merge 합니다. 마지막으로 출시된 master 브랜치에서 버전 태그를 추가합니다.
